### ISSUE TITLE
User: Bug report - id: relationship to recipient

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssareportchangesletter#4]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `relationship to recipient`
Steps to reproduce | id: relationship to recipient
Question field: How are you related to "recipient name"
Expected behavior | The "How are you related?" text field would disappear if Other was unchecked
What happened instead | If you select choice: Other the text field "How are you related?" appears.  However, if you unselect "Other" the text box does not go away and you are unable to move forward without filing it out
Other information | Form: Report of benefits and Dedicated Account - AMS
Variable being sought | `rep_payee.relationship`

**Comment by stevejaubz** [comment]
resolved in 12/21 branch push
