### ISSUE TITLE
User: Bug report - id: address

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssareportchangesletter#5]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `address`
Steps to reproduce | id: address

Capitalize address fields
if your browser autofills the telephone number editing is difficult. Can only backspace the last digit. 

I noticed that source has  datatype: tel but it did not validate the telephone number, only formats if you type in yourself
Expected behavior | n/a
What happened instead | n/a
Other information | Form: Report of benefits and Dedicated Account
Source
- AMS
Variable being sought | `rep_payee.address.address`

**Comment by stevejaubz** [comment]
tel enters into PDF in a clean format whether the validation formats with the (xxx) xxx-xxx or the numbers are input xxxxxxxxx without separators
