### ISSUE TITLE
User: Bug report - Progress menu

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssareportchangesletter#6]
&nbsp; | &nbsp;
-------|------------------------------------
Page title | Your signature
Steps to reproduce | Progress menu has Receipts highlighted for address and signature
Expected behavior | will upload screenshot
What happened instead | n/a
Other information | Form: Report of benefits and dedicated account 
- AMS
Variable being sought | `rep_payee.signature`

**Comment by stevejaubz** [comment]
![Screen Shot 2020-12-17 at 3 24 58 PM](https://user-images.githubusercontent.com/66577647/102539910-4b658980-407c-11eb-8db8-9bcb60cc156d.png)

**Comment by stevejaubz** [comment]
resolved signature and addtional section issues - moved rep address into information about you section
