### ISSUE TITLE
User: Bug report - PDF Formatting 

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssareportchangesletter#7]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `download`
Steps to reproduce | PDF Formatting Issues
Expected behavior | Text sizing is inconsistent
- question 8  dollar amount very large 
- signature date, relationship, telephone number very large

Question  7  difficult to read, the lines cut through my answer. Might want to fill in white
What happened instead | n/a
Other information | Report of benefits and Dedicated Account
Source
- AMS
Variable being sought | `pdf_report`

**Comment by stevejaubz** [comment]
Resolved above in branch.... would like to remove boxes from questions that do not need to be filled in to make it clear to the user that they were not supposed to have anything there
