### ISSUE TITLE
User: Bug report - id: events - add address to prompt

### ISSUE THREAD

**Issue by nonprofittechy** [nonprofittechy/docassemble-ssareportchangesletter#9]
&nbsp; | &nbsp;
-------|------------------------------------
Question ID | `events`
Steps to reproduce | id: events
Expected behavior | if the beneficiary moved the form needs like their new address. Add this to the prompt that appears if client_moved is checked 

"Please explain why Aubrie Souza moved and provide their new address"
What happened instead | -
Other information | Report of benefits and Dedicated Account
Source
AMS
Variable being sought | `had_felony`

**Comment by stevejaubz** [comment]
![Screen Shot 2020-12-18 at 12 38 12 PM](https://user-images.githubusercontent.com/66577647/102643879-eff3d400-412d-11eb-9c49-10c5c554db83.png)

**Comment by stevejaubz** [comment]
added character limits to both fields on this page - spill over does not go into appendix currently

**Comment by stevejaubz** [comment]
resolved character limit
